export const EmojiTable: Record<string, string[]> = {
    '😀': ['happy', 'joy', 'delight'],
    '😊': ['smile', 'cute', 'smiling', 'blushing'],
    '😁': ['grin', 'grinning'],
    '😉': ['wink', 'winking', 'winky face'],
    '🙃': ['upside-down', 'upside down'],
    '😅': ['oops', 'mistake', 'accident'],
    '😇': ['angel', 'halo', 'innocent'],
    '🥰': ['crush'],
    '😍': ['in love', 'loves', 'heart-eyes', 'crazy over', 'crave'],
    '😚': ['kiss', 'kissing', 'kisses'],
    '🤫': ['shush', 'quiet', 'silent'],
    '😋': ['yum', 'yummy', 'savour', 'savouring', 'delicious', 'tasty'],
    '🤔': ['think', 'thinking'],
    '😐': ['meh', 'expressionless', 'neutral'],
    '😮‍💨': ['relief', 'close call', 'whistle', 'exhale'],
    '🤥': ['lie', 'lying', 'lies', 'lier', 'pinocchio'],
    '🤤': ['droll', 'drolling', 'craving'],
    '😴': ['sleep', 'sleepy', 'sleeping', 'sleeps', 'slept'],
    '🤒': ['sick', 'sick of', 'ill'],
    '😞🕴🏻': ['alone', 'lonely', 'loner'],
    '🤪': ['crazy', 'sicko', 'psycho', 'dumb', 'stupid'],
    '🥵': ['sweat', 'sweating', 'heat stroke', 'heat'],
    '🥶': ['cold', 'freeze', 'frozen', 'freezing'],
    '🤯': ['shocked', 'mind blown', 'incredible', 'shock'],
    '🥴': ['drunk', 'wasted', 'alcoholic'],
    '😵‍💫': [
        'confused',
        'dizzy',
        'dizziness',
        'spiral',
        'whoa',
        'hypnotize',
        'hypnotized'
    ],
    '🤠': ['cowboy', 'wild west'],
    '🥳': ['celebration', 'partying', 'fun time'],
    '🥺': ['pleading', 'plead', 'mercy', 'beg', 'begging'],
    '😳': ['embarrassing', 'embarrased', 'embarrassment', 'oops', 'horror'],
    '😱': ['shake', 'fear', 'scared', 'scary', 'scream', 'yell'],
    '😭': ['cry', 'sob', 'sad', 'tears', 'tear', 'crying', 'cries'],
    '🥱': ['tired', 'yawn', 'bored', 'boring', 'yawning'],
    '😡': ['mad', 'angry', 'rage', 'enraged', 'furious'],
    '😈': ['devil', 'evil', 'imp'],
    '💀': ['death', 'skull', 'dead', 'deadly'],
    '💩': ['poo', 'poop', 'shit', 'dung'],
    '🤡': ['clown', 'fool', 'jester'],
    '👻': ['after life', 'ghost', 'haunt', 'haunted'],
    '👽': ['UFO', 'extraterrestrial', 'alien'],
    '🤖': ['robot', 'ai'],
    '😺': ['cat'],
    '💔': ['heartbroken', 'heartache', 'heartbreak'],
    '❤️‍🔥': ['passion', 'lust'],
    '❤': ['heart', 'love'],
    '💋': ['lip', 'lips', 'kiss', ' lipstick'],
    '💥': ['boom', 'explode', 'explosion', 'exploded'],
    '🕳': ['hole', 'pit'],
    '👋': ['wave', 'waving', 'goodbye', 'hello'],
    '✋': ['hand', 'palm'],
    '👌': ['ok', 'no problem', 'of course', 'sure'],
    '👍': [
        'good',
        'thumbs up',
        'thumb',
        'great',
        'like',
        'likes',
        'enjoy',
        'enjoys'
    ],
    '👎	': ['bad', 'thumbs down', 'dislike', 'dislikes'],
    '🤞': ['cross', 'fingers crossed', 'good luck', 'luck'],
    '🤙	': ['call', 'call me'],
    '👏': ['claps', 'clap', 'clapping'],
    '🤏🏻': ['small', 'tiny', 'pinch'],
    '👆': ['up'],
    '👇': ['down'],
    'You Emoji': ['you'],
    '🤝': ['handshake', 'agreement', 'meeting', 'deal', 'agreed', 'agree'],
    '🙏	': ['thanks', 'thank', 'thank you', 'pray', 'praying', 'thanking'],
    '👂': ['all ears', 'ear', 'ears'],
    '👃': ['nose', 'smell', 'smelly'],
    'palm up hand emoji': ['offers', 'offer', 'give', 'gives'],
    '💪': [
        'muscle',
        'muscles',
        'flex',
        'strong',
        'strength',
        'powerful',
        'power'
    ],
    '🦵': ['leg', 'legs', 'limb'],
    '🦶': ['foot', 'feet', 'stomp', 'kick'],
    '🧠': ['brain', 'intelligent', 'intelligence', 'smart'],
    '🦷': ['tooth', 'teeth', 'dentist'],
    '🦴	': ['bone', 'bones', 'skeleton'],
    '👀': ['eyes', 'look', 'looking'],
    '👁	': ['eye'],
    '👅': ['tongue'],
    '👄': ['mouth'],
    '👹': ['mosnter', 'orge', 'troll', 'creature'],
    '👶': ['baby', 'infant', 'young'],
    '🚶🏻': ['walks', 'walk'],
    '👧': ['girl', 'girly'],
    '👭': ['girls', 'women'],
    '👦': ['boy', 'boyish'],
    '👬': ['boys', 'guys', 'men'],
    '👨': ['man', 'men', 'adult'],
    '👩': ['woman', 'women'],
    '👵': ['grandma', 'grandmas', 'grandmother'],
    '👴': ['grandpa', 'grandpas', 'grandfather'],
    '🙋‍♂️👈': ['im', 'myself', 'me', 'i'],
    '🙅‍♂️': ['no', 'nah uh', 'no way', 'nope', 'dont', "don't", 'do not'],
    '🤦‍♂️': ['disbelief', 'facepalm', 'frustrated', 'frustration'],
    '🤷‍♂️': ['shrug', 'doubt', 'careless'],
    '🏃‍♂️': ['run', 'running', 'runs'],
    '💃': ['dance', 'dancing'],
    '👨‍🎓': ['student', 'study', 'studies', 'studying'],
    '👨‍⚕️': ['doctor', 'healthcare', 'therapist'],
    '🦸	': ['super', 'hero', 'superhero', 'superpower'],
    '🧙': ['mage', 'magic', 'wizard', 'sorcerer'],
    '🧚': ['fairy', 'fairy tale'],
    '🧜‍♂️': ['neptune', 'posidon', 'merman'],
    '🧜‍♀️': ['mermaid'],
    '👨‍👩‍👧‍👦': ['family'],
    '👣': ['footprint', 'footprints', ' tracks'],
    '🐒': ['monkey'],
    '🐶': ['dog', 'pet'],
    '🐺': ['lone wolf', 'wolf'],
    '🐈‍⬛': ['bad luck', 'unlucky', 'cursed'],
    '🤰🐷': ['pig', 'fat', 'hog', 'obese'],
    '🐐': ['goat', 'best', 'greatest', 'greatest of all time'],
    '🦒': ['tall', 'giraffe'],
    '🦨': ['skunk', 'stink', 'smelly'],
    '🐓': ['chicken', 'rooster'],
    wing: ['wing', 'wings'],
    '🐉': ['dragon', 'dragging', 'myth', 'mythical'],
    '🐋': ['whale', 'whales'],
    '🐋➕': ['big', 'huge', 'gigantic'],
    '🕊': ['peace', 'dove', 'bird'],
    '🐟': ['fish'],
    '🐌': ['snail', 'slow'],
    '🦟': ['fly', 'mosquito', 'bite', 'pest'],
    '🌺': ['flower'],
    '🌱': ['plant', 'grow', 'growth', 'seed', 'seedling'],
    '🍀': ['luck', 'goodluck', 'lucky'],
    '🍋': ['sour', 'lemon', 'lemons'],
    '🍋🥤': ['lemonade'],
    '⚙️🔧': ['make', 'made', 'making'],
    '📈🛠️': ['progress', 'upgrade'],
    '⌚❓': ['when'],
    '📍🗺️❓': ['where'],
    '😴💭': ['dreams', 'dream', 'dreaming'],
    '😴💭😱': ['nightmare'],
    '🤔💭': ['thinking', 'thinks', 'think', 'thought'],
    '💭💡': ['idea', 'creative', 'creativity'],
    '📍🗺️': ['location', 'place'],
    '🌶': ['spicy', 'spice'],
    '🍫': ['chocolate', 'choco'],
    '🍬': ['sweet', 'candy'],
    '🍨': ['dessert'],
    '🍻': ['beer', 'bar', 'drink', 'alcohol'],
    '🍷': ['wine', 'alcohol'],
    '🔪🩸': [
        'kill',
        'murder',
        'murderer',
        'killer',
        'assassination',
        'assassinate'
    ],
    '🧊': ['ice', 'cold'],
    '❌': [
        'not',
        'anti',
        'against',
        'counter',
        'counters',
        'oppose',
        'opposition',
        'contrary'
    ],
    '🛑': ['stop', 'stopped'],
    '⛔': ['no entry', 'ban', 'banned'],
    '🍕': ['pizza', 'food'],
    '🌱🧬': ['life'],
    '⏰': ['time'],
    '🌙': ['night', 'nighttime'],
    '⚠️': ['danger', 'warning'],
    '♨️': ['warm', 'steam', 'steaming', 'springs'],
    '🔥': ['hot', 'burn', 'flame', 'heat', 'burning', 'fire', 'lit'],
    '⚡': ['electric', 'electricity', 'bolt', 'voltage', 'zap'],
    '🌞': ['sun', 'sunny', 'summer', 'day', 'daytime'],
    '🎉': ['celebrate', 'party'],
    '📚': ['book', 'reading']
}

export const stopWords: string[] = [
    'am',
    'is',
    'are',
    'and',
    'or',
    'the',
    'a',
    'an'
]

export function test(phrase: string) {
    const tokens: string[] = phrase.toLowerCase().split(/\s+/)
    const emojis: string[] = []
    tokens.forEach((token) => {
        if (!stopWords.includes(token)) {
            for (const emoji of Object.keys(EmojiTable))
                if (EmojiTable[emoji].includes(token)) emojis.push(emoji)
        }
    })
    const emojis_rep: string = emojis.join(' ')
    return emojis_rep
}
