import { WordPack } from "./WordPack.model"

export const EasyPack: WordPack = {
    pack: [
    'ad','abs','ace','act','add','age','ago','aim','air','aid',
    'all','any','ape','app','arc','arm','art','ash','ask','axe',
    'ai','as','bad','bag','bam','ban','bar','bat','bed','beg','bay',
    'bet', 'bio','bot','bow','bow','boy','bra','bro','bug','bum',
    'bug','bus','but','buy','bye','bi','bo','by','car','cat',
    'can','cap','cog','cop','cry','cub','cue','cum','dad','daw',
    'day','did','die','dig','dim','dog','dot','dry','due','duo',
    'ear','eat','eco','egg','ego','era','emo','end','eta','eye',
    'ex','eel','fan','fap','far','fat','fit','fix','fin','flu',
    'fly','for','foe','fog','fox','fry','fun','fur','go','gag',
    'gap','gas','gay','gel','gem','gen','get','gif','gig','gin','git',
    'god','got','gum','gun','gut','guy','gym','haha','hat','hey',
    'her','hit','hog','hot','hop','hue','hi','huh','hub','hug','how',
    'him','he','hehe','hoe','hay','id','icy','ill','imp','inn',
    'ink','ivy','if','in','is','it','jab','jam','jar','jaw','jet',
    'jew','job','jog','joy','key','kid','lab','lad','lag','lap',
    'lay','lid','lie','lip','low','low','me','mac','map','man',
    'max','mix','mob','mod','mud', 'mama','my','no','nap','net',
    'nod','nut','of','oak','odd','old','oil','out','owl','oh',
    'oof', 'ok', 'on', 'op','or','papa','pat','paw','pee','pet',
    'pit','put','pi','ran','rap','rat','red','rizz','rip','rot',
    'row','rub','run','sad','sat','saw','sex','say','she','shy','sue',
    'sir','ski','sis','sin','sky','six','spa','spy','sun','tax',
    'tag','tap','ten','tic','tie','ton','toy','try','tub','up','van',
    'us','we','wet','who','why','win','wow','was','you','yay','yes','zap','zoo'
],
    difficulty: 1  
}

export const MediumPack: WordPack = {
    pack: [
    'ache','acid','afar','amen','apex','anus','anti','aqua','area','army',
    'away','babe','baby','back','bais','ball','bait','band','bane','bang','bank','bolt',
    'bard','barn','bark','bead','beak','bean','bear','beef','beer','bell',
    'belt','bend','beta','bill','bind','bird','blow','blue','boar','boat',
    'body','boil','bomb','bone','boob','book','boss','bowl','brag','buff',
    'bulk','bull','busy','bust','burn','butt','cafe','cake','call','calm',
    'camo','camp','cane','cant','cape','come','card','care','cart','case','cash',
    'cast','cave','cell','cent','chat','clan','clay','crab','claw','clip','clit',
    'coat','club','clue','cock','coil','coin','cold','coma','cook','cool',
    'copy','core','cost','crow','cube','cult','cute','cyan','dang','date',
    'deal','dear','debt','deer','deep','demo','deny','dice','dick','dino',
    'dire','dive','dock','doll','done','down','drug','drum','draw','duck',
    'dude','duel','dumb','dune','dust','each','ease','edit','echo','else',
    'envy','even','ever','evil','exam','edge','exit','fail','fair','fake','fall',
    'fang','farm','fart','fear','faze','fast','fell','film','fill','five',
    'fizz','flag','flex','flow','fold','food','fork','form','fort','foul',
    'four','free','frog','fuck','fuel','funk','fuze','feed','feel','flat',
    'foil','font','fool','flee','flop','flaw','file','game','gang','gave',
    'gaze','gear','geek','germ','giga','girl','give','glad','glee','glow',
    'gold','golf','gram','grey','grid','grow','hack','half','hall','hand',
    'hash','hawk','haze','hear','heat','heil','hide','high','hill','hint',
    'heal','hail','harm','herb','herd','hope','hour','hush','hump','hose',
    'hobo','holo','home','hood','hook','hunt','hurt','hype','idle','idol',
    'inch','iris','icon','idea','ibex','isle','itch','jail','jazz','jedi',
    'jeep','jinx','jizz','joke','join','juke','jury','jump','junk','keen',
    'keep','kelp','kick','kind','king','kiss','kiwi','kane','kart','know',
    'lack','lady','lake','lame','late','lava','leaf','lean','left','less',
    'lewd','lick','lier','life','lift','limb','like','link','lite','lion',
    'line','live','load','lock','long','lose','loud','love','lung','lure',
    'luck','lust','lute','lynx','mace','made','male','mall','mail','mark',
    'math','mate','maze','mask','meal','mean','mind','mock','moon','muse',
    'mice','mild','mint','miss','moan','monk','move','mule','navy','nail',
    'neck','node','nope','nest','next','nice','nine','noob','norm','note',
    'nuke','null','numb','oath','obey','okay','open','ouch','oven','over',
    'pace','pact','page','pain','pair','pale','park','pass','past','peak',
    'pawn','pear','peek','pelt','perk','pimp','pipe','plea','play','plan',
    'plus','plot','poke','pong','post','pray','prey','pure','push','pony',
    'poor','pool','pork','porn','puke','pull','pump','puma','pyro','quad',
    'quip','quiz','quit','race','rack','rage','raid','rain','ramp','rank',
    'rape','rant','rare','rate','rave','read','real','rear','reef','rent',
    'rich','ride','ring','rink','ripe','road','rune','roam','roar','robe','rock','rule',
    'role','roll','roof','room','root','rope','rose','ruby','rust','rush',
    'sack','safe','saga','said','sail','sale','salt','same','sane','sand',
    'sank','save','scam','scan','scum','seak','seat','seed','seek','seen',
    'self','sell','semi','sexy','suit','shed','shit','shiv','sick','shut','shoe',
    'shot','sigh','side','sign','silo','simp','slam','slap','slay','slip',
    'slow','slot','snow','soak','soap','sock','soda','sofa','soft','soil',
    'sold','sole','solo','song','soul','soup','sour','span','spam','spar','size',
    'spin','spit','stab','star','stay','step','stew','stun','such','suck',
    'sulk','sumo','sure','surf','swat','swim','sync','tact','taco','take',
    'tale','talk','tall','tank','tape','tart','taxi','teen','tear','text',
    'thai','thin','they','thug','tick','tide','tier','tile','till','tilt',
    'time','tint','tiny','tire','tits','toad','toes','told','toll','tomb',
    'tone','took','tool','toss','town','tour','trap','tray','tree','trio',
    'trip','tube','turn','twat','twig','twin','ugly','undo','unit','upon',
    'urge','used','user','vain','vape','vase','vein','verb','vent','very',
    'vibe','vice','vine','visa','vote','wack','wage','wake','wall','wand',
    'wank','want','ware','wart','warn','warm','wash','wave','wear','weed',
    'weak','were','what','whoa','whom','wipe','wide','wiki','wife','wifi','wild',
    'will','wimp','wind','wine','wink','wire','wise','wish','woke','wolf',
    'womb','wood','woof','work','word','wore','worm','worn','wrap','xray','yale',
    'yard','yarn','year','yawn','yell','yeti','yoga','yolk','your','yoyo','zero',
    'zinc','zone','zoom',


    "About", 'angel', 'Abort', "Above", 'acorn', "Abuse", "Acute", 'adapt', "Actor", "Admit", 'adore', "Adopt", "Adult", "After", "Again",
    "Agent", "Agree", 'avail', "Ahead", 'amuse', "Alarm", "Album", "Alive", 'alias', 'alpha','align', "Alike", "Along", "Alone", "Alter",
    "Among", "Anger", "Angry", 'ancle', "Apart", 'arise', 'atone', "Apple", 'apply', 'annoy', 'anime', "Arena", "Array", "Aside", "Asset", "Audio",
    "Avoid", "Award", 'awake', 'await', "Aware", 'batch', 'bicep', "Badly", "Baker", 'Basis' ,"Basic", "Bases", "Beach", "Began", "Begin",
    "Begun", 'Bagel', 'bored', "Being", 'beard', 'bible', 'badge', "Below", "Bench", "Billy", "Black", "Blame", 'blink', "Blind", "Block", "Blood",
    "Board", "Booth", 'booty', 'booze', 'brake', "Brand", 'brain', "Bread", 'belly', 'beret' ,"Break", "Breed", "Brief", "Bring", "Broad", "Broke", 'bliss', 'bluff',
    "Brown", 'bogey', "Build", 'bison', "Built", 'bunch', 'devil', "Bunny", "Burst", "Cable", 'chimp', 'chunk', 'cider', "Calif", 'child', "Cause", "Chain", "Chair",
    "Chase", 'coral', 'creme', "Cheap", 'champ', 'cheer', "Check", 'chart', 'cease', 'canal', "Chest", 'cache', 'cadet', "China", "Chose", 'clash', "Civil", 'class', "Claim", 'clear', "Clean", "Click",
    "Close", 'clone', 'clown', 'color', 'comet', 'cyber', "Coach", "Could", 'candy', "Count", 'chess', 'cramp', 'crush', "Court", 'crack', "Craft", 'creek', "Crash", "Cream", "Crime", "Cross",
    "Crown", "Curve", 'couch', 'coupe', "Cycle", "Daily", "Dance", "Dated", "Death", 'dried', 'decoy', 'delta', "Dealt", 'debug', "Debut", 'depot', "Depth",
    "Doing", 'doubt', 'droll', "Dozen", "Draft", 'derby', "Drama", "Drawn", "Dream", "Dress", 'dairy', "Drill", "Drink", "Drive",
    "Drove", 'drown', 'dwarf', "Dying", 'elbow', 'expel', "Eager", "Early", 'emote', "Earth", "Eight", "Elite", 'enjoy', 'ensue', "Empty", 'erase', "Enemy", 'erupt', "Enter",
    "Entry", 'every', "Equal", 'ebony', "Error", 'exfil', "Event", "Exact", "Exist", "Extra", 'fatal', 'fluff', "Faith", 'fancy', "False", "Fault",
    "Fibre", "Field", "Fifth", "Fight", "Final", "First", 'faint', 'fairy', "Fixed", 'faded', 'fence', 'flame', 'flick', "Flash", 'fabel', "Fleet", "Float",
    "Floor", "Focus", "Force", "Forth", "Forum", "Found", "Frame", "Frank", 'fraud', "Fresh", "Front",
    "Fruit", "Funny", "Given", "Glass", 'genes', "Globe", 'goofy', 'godly', 'glory', 'grown', "Going", 'ghost', "Grace", "Grand", "Grass", "Great",
    "Green", "Gross", 'gauge', "Guard", "Guess", "Guest", "Guide", 'honey', "Happy", 'haste', 'havoc', "Harry", 'haunt', "Heart", "Heavy",
    "Hence", "Horse", "Hotel", 'hyper', "House", 'honor', 'hound', 'humor', 'hurry', "Human", "Ideal", 'idiot', 'ingot', 'intel', 'imply', 'incel', "Image", 'inbox', "Index", "Inner", "Input",
    "Issue", "Juice", "Joint", 'jewel', "Judge", "Known", 'knock', 'knife', "Label", 'lance', "Laser", "Laugh", "Layer",
    "Learn", 'lease', "Legal", 'liver', "Level", "Light", 'lobby', 'loner', 'loyal', "Limit", 'lunar', "Logic", "Loose", "Lower", "Lucky", "Lying",
    "Magic", "Major", "Maker", "March", "Match", 'maybe', "Mayor", 'medic', 'micro', "Media", "Metal", "Minor", 'modem', "Model",
    "Money", 'manor', 'marry', "Month", 'maple', "Moral", "Motor", "Mouth", "Movie", "Mount", "Mouse", "Mouth", "Music",
    "Never", "Needs", "Never", 'night', "North", 'noise', "Novel", "Nurse", 'onion', "Ocean", "Offer", "Often", "Order",
    "Other", 'opera', 'oasis', 'occur', 'omega', 'olive', 'owned', 'ozone', 'ounce', 'optic', 'organ', "Ought", "Paint", "Paper", 'pupil', 'purse', "Party", 'pulse', "Patch", "Peace", "Phone", "Photo", 'prior', "Piece",
    "Pilot", 'pilar', 'plaza', 'plush', 'pixel', 'place', 'plate', 'prank', 'plane', 'plain', 'pizza', 'pitch', 'pivot', 'pinky', "Pound", "Power", "Press", 'prick', "Price", 'panda', 'pearl', 'petty', 'parry', 'paste', 'penis', "Prize", 'palet', "Proof", "Proud", "Prove", "Queen",
    "Quiet", 'quack', 'quick', "Quite", 'quest', 'queue', "Raise", 'relay', 'remix', 'reply', 'rubby', 'rotor', 'rhyme', 'rhino', 'raven', "Range", 'rider', 'riper', "Ratio", "Ready", "Refer", "Right", "Rival", "River",
    "Roman", "Rough", "Round", 'razor', "Route", 'realm', 'recap', "Royal", "Rural", "Score", "Serve", "Seven", "Shape",
    "Sharp", 'shark', "Sheet", 'sooth', "Shelf", 'stall', "Shell", 'snout', "Shift", 'spoke', "Shirt", "Shock", "Shoot", "Short", "Shown",
    "Sight", "Since", 'syrup', "Sixth", 'sword', 'sonar', 'swirl', "Skill", "Sleep", 'spank', 'sneak', "Slide", 'strap', 'snack', 'spice', "Small", 'stove', "Smart", 'smack', "Smile", "Smith",
    "Smoke", "Solid", "Solve", 'swarm', 'swift', "Sorry", 'shine', 'shove', "Sound", 'shave', "South", 'shade', "Space", 'spell', 'shake', 'speak', "Speed", "Spend", "Spent",
    "Split", "Sport", 'slash', 'slime', "Staff", 'stack', 'skirt', 'stain', "Stage", 'stash', 'sever', "Stake", "Stand", 'saber', 'steal', "Start", 'stone', "State", 'stiff', "Steel","Stick",
    "Still", "Stood", 'sewer', 'siren', "Store", 'semen', "Storm", 'scary', "Story", "Strip", 'scale', "Stuck", 'sauce', "Study", "Stuff","Style",
    "Suite", "Sugar", "Super", 'skull', 'sigil', 'silly', "Sweet", "Table", "Taken", "Taste", "Teach", "Teeth","There",
    "These", "Thick", "Thing", 'tense', "Think", "Third", "Those", "Three", 'topaz', 'today', "Throw", "Threw", "Theme", 
    "Think", "Throw", "Threw", "Throw", 'throb', 'thumb', "Thrown", 'token', "Tight", 'torch', "Times", "Title", "Total", "Touch", 
    "Tough", "Tower", 'towel', 'tumor', 'toxic', 'toxin', "Track", 'thief', "Trade", 'train', "Trail", 'tripy', 'tenth', 'troll', "Trait", "Trend", "Trial", 'thank', "Trust", 'truck', "Truth", 
    "Twice", 'twist', "Under", "Undue", 'untie', 'unzip', "Union", "Unity", "Until", "Upper", "Urban", "Usage", "Usual", 
    "Valid", 'vague', 'valor', 'valve', 'venue', 'viper', 'vegan', 'vivid', 'villa', "Value", "Video", "Visit", 'vodka', 'vouch', "Vital", 'vomit', "Voice", "Watch", "Water", "Wheel", "Where", 
    "Which", "While", "White", "Whose", 'whore', "Worse", "Worst", "Worry", 'wrist', "Would", "Write", "Wrote", 
    "Wrong", "Wound", 'woman', 'world', 'wrath', "Worth", "Young", "Youth", "Yield", 'yacht', 'yummy'],
    difficulty: 2
}

export const HardPack: WordPack = {
    pack:   
    [
        'Abacus', 'Abject', 'Ablaze', 'avenue', 'Abroad', 'Abrupt', 'Absorb', 'Abused', 'Accept', 'Access', 'Accuse',
        'Admire', 'Adored', 'Advant', 'Advise', 'Affect', 'Afford', 'Afraid', 'Agreed', 'Alarms', 'Albeit', 'active',
        'Alerts', 'Aligns', 'Allege', 'Anyone', 'Apache', 'Appeal', 'Appear', 'around', 'Appeal', 'Arched', 'author',
        'Almond', 'Almost', 'Alpaca', 'Alumna', 'Ambush', 'Amount', 'Amused', 'Anally', 'Anchor', 'advice',
        'Arches', 'Ardeny', 'Argued', 'Arisen', 'Armada', 'Arrays', 'Arrive', 'Artful', 'Artist', 'Ascent',
        'Assign', 'Assure', 'Asthma', 'Athena', 'Attack', 'Attain', 'Attire', 'August', 'Aurora', 'Awaken', 
        'Abates', 'Abused', 'Accent', 'Accuse', 'Affair', 'Affect', 'always', 'animal', 'answer', 'anyway',
        'Better', 'Beyond', 'Bishop', 'Border', 'Bottle', 'Bottom', 'Bought', 'Branch', 'Breath',
        'Bridge', 'Bright', 'Broken', 'Budget', 'Burden', 'Bureau', 'Button', 'Baffle', 'Balcon', 'Baldly',
        'Ballot', 'Ballet', 'Bamboo', 'Banter', 'Barbed', 'Barren', 'Basalt', 'Basket', 'Battle', 'Beachy',
        'Beacon', 'Beaker', 'Beamed', 'Beaten', 'Beauty', 'Bedlam', 'Before', 'Behind', 'Belfry', 'Bended',
        'Berate', 'Beside', 'Bestir', 'Betide', 'Bigger', 'Billow', 'Bindle', 'Binged', 'Binned', 'Bisect',
        'Bitten', 'Bladed', 'Blamed', 'Blazed', 'Blonde', 'Blotch', 'Boated', 'Bodily', 'Boiled', 'Borrow', 
        'Bouncy', 'Bovine', 'Brewer', 'Broker', 'Bruise', 'Brutal', 'Bucket',
        'Camera', 'Cancer', 'Cannot', 'Carbon', 'Career', 'Castle', 'Casual', 'Caught', 'Center', 'Centre',
        'Chance', 'Change', 'Charge', 'Choice', 'Choose', 'Chosen', 'Church', 'Circle', 'Client', 'Closed',
        'Closer', 'Coffee', 'Column', 'Combat', 'colide', 'Coming', 'Common', 'Comply', 'Copper', 'Corner', 'Costly',
        'County', 'Couple', 'Course', 'Covers', 'Create', 'Credit', 'Crisis', 'Custom', 'Damage', 'Danger',
        'Dealer', 'Debate', 'Decade', 'Decide', 'Defeat', 'Defend', 'Define', 'Degree', 'Demand', 'Depend',
        'Deputy', 'Desert', 'Design', 'Desire', 'Detail', 'Detect', 'Device', 'Differ', 'Dinner', 'Direct',
        'Doctor', 'Dollar', 'Domain', 'Double', 'Driven', 'Driver', 'During', 'Easily', 'Eating', 'Editor', 
        'Effect', 'Effort', 'Eighth', 'Either', 'Eleven', 'Emerge', 'Empire',
        'Employ', 'Enable', 'Ending', 'Energy', 'Engage', 'Engine', 'Enough', 'Ensure', 'Entire', 'Entity',
        'Equity', 'Escape', 'Estate', 'Ethnic', 'Exceed', 'Except', 'Excess', 'Expand', 'Expect', 'Expert',
        'Export', 'Extend', 'Extent', 'Fabric', 'Facing', 'Factor', 'Failed', 'Fairly', 'Fallen', 'Family',
        'Famous', 'Father', 'Fellow', 'Female', 'Figure', 'Filing', 'Finger', 'Finish', 'Fiscal', 'Flight',
        'Flying', 'Follow', 'Forced', 'Forest', 'Forget', 'Formal', 'Format', 'Former', 'Foster', 'Fought',
        'Fourth', 'French', 'Friend', 'Future', 'Garden', 'Gather', 'Gender', 'German', 'Global', 'Golden',
        'Ground', 'Growth', 'Guilty', 'Gabble', 'Gadget', 'Gainly', 'Gallop', 'Gamble', 'Gamely', 'Gazing',
        'Geneva', 'Gently', 'Giggle', 'Ginger', 'Girdle', 'Gladly', 'Glazed', 'Glitch', 'Gloomy', 'Glowed',
        'Gluten', 'Goggle', 'Gossip', 'Graded', 'Grains', 'Grassy', 'Grater', 'Gravel', 'Grease', 'Greedy',
        'Groove', 'Grudge', 'Guided', 'Guitar', 'Gunner', 'Gurgle', 'Gabber', 'Gables', 'Gaffes', 'Gaiety',
        'Gainer', 'Gander', 'Gangly', 'Gawked', 'Gelled', 'Ghetto', 'Hacker', 'Haggle', 'Halter', 'Hamlet',
        'Handle', 'Hangar', 'Hanger', 'Happen', 'Harass', 'Harbor', 'Hardly', 'Harmed', 'Hazard', 'Heated',
        'Heaven', 'Herbal', 'Hereby', 'Heroes', 'Herpes', 'Hinder', 'Hinged', 'Hissed', 'Hoarse', 'Homily',
        'Hooded', 'Hoofed', 'Hookah', 'Hornet', 'Horrid', 'Horsed', 'Hosted', 'Humble', 'Hunter',
        'Hurled', 'Hurray', 'Hurted', 'Hutter', 'Hybrid', 'Hyster', 'Hacked', 'Hagged', 'Hailed', 'Hailer',
        'Halers', 'Haling', 'Handed', 'Headed', 'Health', 'Height', 'Hidden', 'Holder', 'Honest',
        'Impact', 'Import', 'Income', 'Indeed', 'Injury', 'Inside', 'Intend', 'Intent', 'Invest', 'Island',
        'Itself', 'Igloos', 'Impala', 'Inning', 'Island', 'Impose', 'Innate', 'Instep', 'Irides', 'Iced-tea',
        'Inward', 'Istles', 'Indent', 'Indium', 'Iodize', 'Infant', 'Influx', 'Infamy', 'Insult', 'Injure',
        'Invest', 'Invite', 'Indict', 'Inland', 'Insane', 'Ironic', 'Iodine', 'Irises', 'Ironed',
        'Issued', 'Innate', 'Jersey', 'Junior', 'Jagged', 'Jamaat', 'Jamjar', 'Jangle',
        'Jargon', 'Jarvis', 'Jellys', 'Jersey', 'Jetsam', 'Jigsaw', 'Jingle', 'Jobbed', 'Jogged', 
        'Joiner', 'Joking', 'Jumble', 'Jumped', 'Junker', 'Jungle', 'Junior', 'Junket', 'Jurors',
        'Juries', 'Jutted', 'Killed', 'Kettle',
        'Keypad', 'Kilter', 'Kimchi', 'Kinder', 'Kingly', 'Kipper', 'Kismet', 'Kitbag',
        'Kitten', 'Kittle', 'Klaive', 'Knight', 'Knives', 'Knocks', 'Knolly', 'Knotty', 'Knower', 'Kokomo',
        'Komodo', 'Koodoo', 'Labour', 'Latest', 'Latter', 'Launch', 'Lawyer', 'Leader', 'League', 'Leaves',
        'Legacy', 'Length', 'Lesson', 'Letter', 'Lights', 'Likely', 'Linked', 'Liquid', 'Listen', 'Little',
        'Living', 'Losing', 'Lucent', 'Luxury', 'Mainly', 'Making', 'Manage', 'Manner', 'Manual', 'Margin',
        'Marine', 'Marked', 'Market', 'Martin', 'Master', 'Matter', 'Mature', 'Medium', 'Member', 'Memory',
        'Mental', 'Merely', 'Merger', 'Method', 'Middle', 'Miller', 'Mining', 'Minute', 'Mirror', 'Mobile',
        'Modern', 'Modest', 'Module', 'Moment', 'Morris', 'Mostly', 'Mother', 'Motion', 'Moving', 'Murder',
        'Museum', 'Mutual', 'Myself',
        'Narrow', 'Nation', 'Native', 'Nature', 'Nearby', 'Nearly', 'Nobody', 'Normal', 'Notice',
        'Notion', 'Number', 'Nacred', 'Nagged', 'Nagger', 'Nailed', 'Namers', 'Naming', 'Napead',
        'Napkin', 'Narked', 'Nassau', 'Natter', 'Navies', 'Nectar', 'Needed', 'Object', 'Obtain',
        'Office', 'Offset', 'Online', 'Option', 'Orange', 'Origin', 'Output', 'Oxford', 'Obeyed',
        'Oblast', 'Obsess', 'Obvert', 'Occult', 'Ocelli', 'Octane',
        'Octant', 'Octave', 'Ocular', 'Oddest', 'Oddity', 'Offend', 'Ogling', 
        'Ogress', 'Oiling', 'Okapis', 'Oldest', 'Oldies',
        'Omelet', 'Omenti', 'Omened', 'Onager', 'Onside', 'Onward', 'Oology', 'Opaque',
        'Openly', 'Opiate', 'Opined', 'Oppose', 'Optics', 'Optima', 'Optime', 'Oracle', 'Orchid',
        'Oregan', 'Orgeat', 'Orient', 'Oroide', 'Orphan', 'Outfit', 'Outing', 'Outlaw', 'Outran', 'Outdid', 
        'Packed', 'Palace', 'Parent',
        'Partly', 'Patent', 'People', 'Period', 'Permit', 'Person', 'Phrase', 'Picked', 'Planet', 'Player',
        'Please', 'Plenty', 'Pocket', 'Police', 'Policy', 'Prefer', 'Pretty', 'Prince', 'Prison', 'Profit',
        'Proper', 'Proven', 'Public', 'Pursue', 'Raised', 'Random', 'Rarely', 'Rather', 'Rating', 'Reader',
        'Really', 'Reason', 'Recall', 'Recent', 'Record', 'Reduce', 'Reform', 'Regard', 'Regime', 'Region',
        'Relate', 'Relief', 'Remain', 'Remote', 'Remove', 'Repair', 'Repeat', 'Replay', 'Report', 'Rescue',
        'Resort', 'Result', 'Retail', 'Retain', 'Return', 'Reveal', 'Review', 'Reward', 'Riding', 'Rising',
        'Robust', 'Ruling',
        'Safety', 'Salary', 'Sample', 'Saving', 'Saying', 'Scheme', 'School', 'Screen', 'Search', 'Season',
        'Second', 'Secret', 'Sector', 'Secure', 'Seeing', 'Select', 'Seller', 'Senior', 'Series', 'Server',
        'Settle', 'Severe', 'Sexual', 'Should', 'Signal', 'Signed', 'Silent', 'Silver', 'Simple', 'Simply',
        'Single', 'Sister', 'Slight', 'Smooth', 'smooch', 'Social', 'Solely', 'Sought', 'Source', 'Soviet', 'Speech',
        'Spirit', 'Spoken', 'Spread', 'Spring', 'Square', 'Stable', 'Status', 'Steady', 'Stolen', 'Strain',
        'Stream', 'Street', 'Stress', 'Strict', 'Strike', 'String', 'Strong', 'Struck', 'Studio', 'Submit',
        'Sudden', 'Suffer', 'Summer', 'Summit', 'Supply', 'Surely', 'Survey', 'Switch', 'Symbol', 'System',
        'Taking', 'Talent', 'Target', 'Taught', 'Tenant', 'Tender', 'Tennis', 'Thanks', 'Theory', 'Thirty',
        'Though', 'Threat', 'Thrown', 'Ticket', 'Timely', 'Timing', 'Tissue', 'Toward', 'Travel', 'Treaty',
        'Trying', 'Twelve', 'Twenty', 'Uberty', 'Udding', 'Uglify', 'Uglier', 'Upping', 'uprove',
        'Upbore', 'Upcast', 'Upcome', 'Update', 'Updive', 'Updove', 'Upheap', 'Upheld', 'Uphill', 'Uphold',
        'Uphove', 'Uplift', 'Uplink', 'Upload', 'Upmost', 'Uprise', 'Uproar', 'Uproot', 'Upsend', 'Upshot',
        'Upsoar', 'Upstay', 'Upstir', 'Upwell', 'Upwind', 'Urbane', 'Urchin', 'Urgent', 'Urinal', 'Usance',
        'Ushaka', 'Usurer', 'Utmost', 'Unable', 'Unique', 'United', 'Unless', 'Unlike', 'Useful', 'Vacant',
        'Vacate', 'Vacuum', 'Vagary', 'Vagile', 'Vagina', 'Vaguer', 'Vainly', 'Valise', 'Valley',
        'Valued', 'Vamped', 'Vandal', 'Varies',
        'Varied', 'Varlet', 'Varnas', 'Vasare', 'Vassal', 'Vatted', 'Vealer', 'Veered', 'Veggie', 'Veiled',
        'Vellum', 'Velour', 'Velure', 'Venial', 'Venice', 'Venous', 'Vented',
        'Verbal', 'Verify', 'Verily', 'Verism', 'Verity', 'Vermes', 'Vermil', 'Vernal', 'Versal', 'Vertex',
        'Vesper', 'Vessel', 'Vested', 'Vetted', 'Vexers', 'Vexils', 'Vexing', 'Vialed', 'Viands',
        'Viewer', 'Vigour', 'Villed', 'Vinery', 'Vineal', 'Vinous', 'Violas',
        'Virago', 'Vendor', 'Versus', 'Victim', 'Vision', 'Visual', 'Volume',
        'Walker', 'Wealth', 'Weekly', 'Weight', 'Window', 'Winner', 'Winter', 'Within', 'Wonder',
        'Worker', 'Wright', 'Writer', 'Yellow', 'Yacker', 'Yammer', 'Yanked', 'Yapper',
        'Yearly', 'Yelled', 'Yodled', 'Yogurt', 'Yonder', 'Yuppie',
        'zipper', 'zodiac', 'zombie'
      ],
      difficulty: 3
}